### ISSUE TITLE
train CA demo - Dead Kernel

### ISSUE THREAD

**Issue by 21dmohan** [williamgilpin/convoca#1]
Firstly, wow, this is amazing work! Thank you for sharing this :)

I am trying to run the demo, but my kernel keeps crashing on the third cell: 

![Screen Shot 2019-06-25 at 2 40 39 PM](https://user-images.githubusercontent.com/35504030/60135939-c421a900-9757-11e9-8fe7-a010b823a86e.png)

Is there some way to fix this? Does me using tensorflow versus tensorflow_gpu make a difference? Or does that simply mean that the specs of my laptop are not good enough: 

![Screen Shot 2019-06-25 at 2 46 50 PM](https://user-images.githubusercontent.com/35504030/60136080-1cf14180-9758-11e9-908e-f10a2d3c7b88.png)

Thank you in advanced!

**Comment by williamgilpin** [comment]
Hi @21dmohan thanks for checking out my project! It shouldn't be that intensive, if I recall correctly I also just used normal tensorflow, not tensorflow GPU. My specs also are pretty comparable:

<img width="569" alt="Screen Shot 2019-06-25 at 15 01 57" src="https://user-images.githubusercontent.com/8154246/60136887-4317e100-975a-11e9-942f-fbb2caeb32b0.png">

Do you happen to know which line in cell 3 is crashing it? Is it potentially a problem with `plt.imshow`?
Or is it definitely the `sess.run`? If the latter, then I'm concerned that this might be a tensorflow version issue---when I wrote this I was using tensorflow 1.

**Comment by 21dmohan** [comment]
Interesting, it appears to be an issue with plt.imshow (the kernel dies at the fourth cell): 

![Screen Shot 2019-06-25 at 3 06 39 PM](https://user-images.githubusercontent.com/35504030/60137161-f8e32f80-975a-11e9-835c-036b6a3c9da2.png)

Do you have any suggestions as to how to fix this?

**Comment by williamgilpin** [comment]
Okay that's a relief. What is `out.shape`? Does matplotlib otherwise work? For example, 

`plt.imshow(np.identity(3))`

**Comment by 21dmohan** [comment]
It appears that my matplotlib is not working: 

![Screen Shot 2019-06-25 at 3 14 41 PM](https://user-images.githubusercontent.com/35504030/60137756-d4885280-975c-11e9-8133-75395089a921.png)

I'll try and sort that out! Thank you so much! I'll let you know if I have any questions :)

**Comment by 21dmohan** [comment]
Quick update (in case someone else has this issue). 

Following the suggestion from this post: https://superuser.com/questions/1406008/jupyter-kernel-dies-when-attempting-a-simple-plot-python

I just had to install nomkl: `conda install nomkl`

**Comment by williamgilpin** [comment]
That's good to know, thank you for posting your fix here. I hope you enjoy the package---let me know if you have any other questions.

**Comment by williamgilpin** [comment]
I'm re-opening this issue because I lost an hour to this bug today. Here is what I needed to do in order to get this code (and all my other tensorflow projects) functional today. 

1. Make a fresh conda environment, but don't use the latest version of python because tensorflow doesn't support it.

`conda create -n nn python=3.6.9`

2. Install the following packages all together. For some reason everything breaks if `nomkl` is installed after the other packages

` conda install nomkl numpy scipy scikit-learn numexpr tensorflow matplotlib`

**Comment by williamgilpin** [comment]
It looks like the latest version of TensorFlow plays nicely with everything, and so I will re-close this issue for now.
