### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Nick45622** [williamgilpin/convoca#2]

**Comment by Nick45622** [comment]
Do you need to write your own test file?

**Comment by williamgilpin** [comment]
hello! i am not sure that i understand

**Comment by rongtongxueya** [comment]
I have the same question.The code of test_ca is not complete. Do you need to write it by yourself? Have you written it yet? After reading your article, I think it is a great work. I am very interested in it and want to reproduce your article. However, I am a novice in this direction and am not good at writing this test file.
